config/routes.rb
Go::Application.routes.draw do

  # Match all URLs
  match ':shortname' => 'namedaliases#go', :as => :shortname

  resources :patternmatches
  resources :namedaliases

end

app/models/alias.rb
class Alias < ActiveRecord::Base
  attr_accessible :shortname, :url, :longname, :description
end

app/models/namedalias.rb
class Namedalias < ActiveRecord::Base
  attr_accessible :shortname, :url, :longname, :description
end

app/models/patternmatch.rb
class Patternmatch < ActiveRecord::Base
  attr_accessible :name, :shortnamepattern, :urlpattern, :priority
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  def index
    @aliases = Alias.all
  end

  def show
    @alias = Alias.find(params[:id])
  end

  def new
    @alias = Alias.new
  end

  def create
    @alias = Alias.new(params[:alias])
    if @alias.save
      redirect_to @alias, :notice => "Successfully created alias."
    else
      render :action => 'new'
    end
  end

  def edit
    @alias = Alias.find(params[:id])
  end

  def update
    @alias = Alias.find(params[:id])
    if @alias.update_attributes(params[:alias])
      redirect_to @alias, :notice  => "Successfully updated alias."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @alias = Alias.find(params[:id])
    @alias.destroy
    redirect_to aliases_url, :notice => "Successfully destroyed alias."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/namedaliases_controller.rb
class NamedaliasesController < ApplicationController
  def index
    @namedaliases = Namedalias.all
  end

  def show
    @namedalias = Namedalias.find(params[:id])
  end

  def new
    @namedalias = Namedalias.new
  end

  def go
    redirect_to Namedalias.find_by_shortname(params[:shortname]).url
  end


  def create
    @namedalias = Namedalias.new(params[:namedalias])
    if @namedalias.save
      redirect_to @namedalias, :notice => "Successfully created namedalias."
    else
      render :action => 'new'
    end
  end

  def edit
    @namedalias = Namedalias.find(params[:id])
  end

  def update
    @namedalias = Namedalias.find(params[:id])
    if @namedalias.update_attributes(params[:namedalias])
      redirect_to @namedalias, :notice  => "Successfully updated namedalias."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @namedalias = Namedalias.find(params[:id])
    @namedalias.destroy
    redirect_to namedaliases_url, :notice => "Successfully destroyed namedalias."
  end
end

app/controllers/patternmatches_controller.rb
class PatternmatchesController < ApplicationController
  def index
    @patternmatches = Patternmatch.all
  end

  def show
    @patternmatch = Patternmatch.find(params[:id])
  end

  def new
    @patternmatch = Patternmatch.new
  end

  def create
    @patternmatch = Patternmatch.new(params[:patternmatch])
    if @patternmatch.save
      redirect_to @patternmatch, :notice => "Successfully created patternmatch."
    else
      render :action => 'new'
    end
  end

  def edit
    @patternmatch = Patternmatch.find(params[:id])
  end

  def update
    @patternmatch = Patternmatch.find(params[:id])
    if @patternmatch.update_attributes(params[:patternmatch])
      redirect_to @patternmatch, :notice  => "Successfully updated patternmatch."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @patternmatch = Patternmatch.find(params[:id])
    @patternmatch.destroy
    redirect_to patternmatches_url, :notice => "Successfully destroyed patternmatch."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/namedaliases_helper.rb
module NamedaliasesHelper
end

app/helpers/patternmatches_helper.rb
module PatternmatchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aliases/_form.html.erb
<%= form_for @alias do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :shortname %><br />
    <%= f.text_area :shortname %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </p>
  <p>
    <%= f.label :longname %><br />
    <%= f.text_area :longname %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/aliases/edit.html.erb
<% title "Edit Alias" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @alias %> |
  <%= link_to "View All", aliases_path %>
</p>

app/views/aliases/index.html.erb
<% title "Aliases" %>

<table>
  <tr>
    <th>Shortname</th>
    <th>Url</th>
    <th>Longname</th>
    <th>Description</th>
  </tr>
  <% for alias in @aliases %>
    <tr>
      <td><%= alias.shortname %></td>
      <td><%= alias.url %></td>
      <td><%= alias.longname %></td>
      <td><%= alias.description %></td>
      <td><%= link_to "Show", alias %></td>
      <td><%= link_to "Edit", edit_alias_path(alias) %></td>
      <td><%= link_to "Destroy", alias, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Alias", new_alias_path %></p>

app/views/aliases/new.html.erb
<% title "New Alias" %>

<%= render 'form' %>

<p><%= link_to "Back to List", aliases_path %></p>

app/views/aliases/show.html.erb
<% title "Alias" %>

<p>
  <strong>Shortname:</strong>
  <%= @alias.shortname %>
</p>
<p>
  <strong>Url:</strong>
  <%= @alias.url %>
</p>
<p>
  <strong>Longname:</strong>
  <%= @alias.longname %>
</p>
<p>
  <strong>Description:</strong>
  <%= @alias.description %>
</p>

<p>
  <%= link_to "Edit", edit_alias_path(@alias) %> |
  <%= link_to "Destroy", @alias, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", aliases_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/namedaliases/_form.html.erb
<%= form_for @namedalias do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :shortname %><br />
    <%= f.text_area :shortname %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </p>
  <p>
    <%= f.label :longname %><br />
    <%= f.text_area :longname %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/namedaliases/edit.html.erb
<% title "Edit Namedalias" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @namedalias %> |
  <%= link_to "View All", namedaliases_path %>
</p>

app/views/namedaliases/index.html.erb
<% title "Namedaliases" %>

<table>
  <tr>
    <th>Shortname</th>
    <th>Url</th>
    <th>Longname</th>
    <th>Description</th>
  </tr>
  <% for namedalias in @namedaliases %>
    <tr>
      <td><%= namedalias.shortname %></td>
      <td><%= namedalias.url %></td>
      <td><%= namedalias.longname %></td>
      <td><%= namedalias.description %></td>
      <td><%= link_to "Show", namedalias %></td>
      <td><%= link_to "Edit", edit_namedalias_path(namedalias) %></td>
      <td><%= link_to "Destroy", namedalias, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Namedalias", new_namedalias_path %></p>

app/views/namedaliases/new.html.erb
<% title "New Namedalias" %>

<%= render 'form' %>

<p><%= link_to "Back to List", namedaliases_path %></p>

app/views/namedaliases/show.html.erb
<% title "Namedalias" %>

<p>
  <strong>Shortname:</strong>
  <%= @namedalias.shortname %>
</p>
<p>
  <strong>Url:</strong>
  <%= @namedalias.url %>
</p>
<p>
  <strong>Longname:</strong>
  <%= @namedalias.longname %>
</p>
<p>
  <strong>Description:</strong>
  <%= @namedalias.description %>
</p>

<p>
  <%= link_to "Edit", edit_namedalias_path(@namedalias) %> |
  <%= link_to "Destroy", @namedalias, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", namedaliases_path %>
</p>

app/views/patternmatches/_form.html.erb
<%= form_for @patternmatch do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shortnamepattern %><br />
    <%= f.text_field :shortnamepattern %>
  </p>
  <p>
    <%= f.label :urlpattern %><br />
    <%= f.text_field :urlpattern %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/patternmatches/edit.html.erb
<% title "Edit Patternmatch" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @patternmatch %> |
  <%= link_to "View All", patternmatches_path %>
</p>

app/views/patternmatches/index.html.erb
<% title "Patternmatches" %>

<table>
  <tr>
    <th>Name</th>
    <th>Shortnamepattern</th>
    <th>Urlpattern</th>
    <th>Priority</th>
  </tr>
  <% for patternmatch in @patternmatches %>
    <tr>
      <td><%= patternmatch.name %></td>
      <td><%= patternmatch.shortnamepattern %></td>
      <td><%= patternmatch.urlpattern %></td>
      <td><%= patternmatch.priority %></td>
      <td><%= link_to "Show", patternmatch %></td>
      <td><%= link_to "Edit", edit_patternmatch_path(patternmatch) %></td>
      <td><%= link_to "Destroy", patternmatch, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Patternmatch", new_patternmatch_path %></p>

app/views/patternmatches/new.html.erb
<% title "New Patternmatch" %>

<%= render 'form' %>

<p><%= link_to "Back to List", patternmatches_path %></p>

app/views/patternmatches/show.html.erb
<% title "Patternmatch" %>

<p>
  <strong>Name:</strong>
  <%= @patternmatch.name %>
</p>
<p>
  <strong>Shortnamepattern:</strong>
  <%= @patternmatch.shortnamepattern %>
</p>
<p>
  <strong>Urlpattern:</strong>
  <%= @patternmatch.urlpattern %>
</p>
<p>
  <strong>Priority:</strong>
  <%= @patternmatch.priority %>
</p>

<p>
  <%= link_to "Edit", edit_patternmatch_path(@patternmatch) %> |
  <%= link_to "Destroy", @patternmatch, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", patternmatches_path %>
</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>